apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-job
  namespace: camunda
  labels:
    app: benchmark
spec:
  activeDeadlineSeconds: 1200
  template:
    metadata:
      labels:
        app: benchmark
    spec:
      #nodeSelector:
      #  workload: benchmark
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "benchmark"
          effect: "NoSchedule"
      containers:
        - name: benchmark
          image: camundacommunityhub/camunda-8-benchmark:main
          imagePullPolicy: Always
          env:
            - name: ORCH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: camunda-credentials
                  key: identity-orchestration-client-token
            - name: JAVA_OPTIONS
              value: >-
                -Dcamunda.client.mode=selfmanaged
                -Dcamunda.client.auth.method=oidc
                -Dcamunda.client.auth.client-id=orchestration
                -Dcamunda.client.auth.client-secret=${ORCH_CLIENT_SECRET}
                -Dcamunda.client.auth.token-url=http://camunda-keycloak:80/auth/realms/camunda-platform/protocol/openid-connect/token
                -Dcamunda.client.grpc-address=http://camunda-zeebe-gateway:26500
                -Dcamunda.client.worker.defaults.max-jobs-active=50
                -Dcamunda.client.execution-threads=10
                -Dcamunda.client.worker.defaults.stream-enabled=true
                -Dcamunda.client.request-timeout=600s
                -Dcamunda.client.job.poll-interval=1ms
                -Dcamunda.client.prefer-rest-over-grpc=false
                -Dbenchmark.startPiPerSecond=100
                -Dbenchmark.startPiIncreaseFactor=0.0
                -Dbenchmark.startRateAdjustmentStrategy=none
                -Dbenchmark.maxBackpressurePercentage=10.0
                -Dbenchmark.taskCompletionDelay=150
                -Dbenchmark.bpmnProcessId=GenericBenchmarkProcess
                -Dbenchmark.autoDeployProcess=false
                -Dbenchmark.payloadPath=file:/config/typical_payload.json
                -Dbenchmark.warmupPhaseDurationMillis=60000
                -Dbenchmark.multipleJobTypes=5
          resources:
            requests:
              cpu: 2
              memory: 3Gi
          volumeMounts:
            - name: payload
              mountPath: /config
              readOnly: true
      volumes:
        - name: payload
          configMap:
            name: payload
      restartPolicy: Never
  backoffLimit: 4
